### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Nate-Wilkins** [mysteriouspants/unity-docker#1]
I'm quite new to Unity3D and I can't seem to find any good examples of a CI pipeline.

Currently working on one but I don't know how long that's going to take. If you have an example I'd love to see it. Thanks!

I'll post an update when I figure it out.

**Comment by mysteriouspants** [comment]
I'm not sure where I'm going to take this project. I found that most CI services don't cache your Docker image, so it re-downloads from Docker Hub every time. This is a multiple-gigabyte download, and takes a long time. It's bad because it takes a long time, and I'm sure the CI services aren't wild about burning so much bandwidth on it, either.

My current project is investigating using AWS CodePipeline for the task, so it would spin up EC2 spot instances using pre-made AMIs, which should be much, much faster than downloading a new Docker image. This may have the added benefit of being able to run on Windows Server spot instances, so you wouldn't have to use the unofficial and unsupported Linux build for your CI needs.

If I return to using Docker I'll update this with some examples and suggestions. It was just a necessary starting point to some experimentation I did in my initial investigation.

**Comment by Nate-Wilkins** [comment]
Yeah the download is atrocious. I am using concourse which does seem to cache specified docker images but since posting my first comment I'm leaning back toward figuring out how to run the unity cli on a windows box... Although that apparently requires a slew of configuration... 

I don't know but I know that Unity has been a pain. I guess I'll see where I end up.
I appreciate the help, thanks!

**Comment by mysteriouspants** [comment]
Unity3D makes a lot of things very easy. I haven't seen that same attention to detail applied to building facilities for you to ensure proper testing for your Unity project.

My recommendation is to extract as much of your business logic into a separate DLL you compile in Visual Studio. Use NUnit/XUnit, Mocks, etc. to build good tests there, then import that into Unity3D. That way the parts that are trivially testable because they're pure C# are done so in mature tools, and the only parts of your application that are not automatically tested are the Unity3D integrations themselves, which should be relatively shallow, therefore easy to reason about and less likely to get wrong.

There's a lot of room for innovation in this space, so if you discover a better way, you should definitely share. :)
